# Generated by Django 5.0.6 on 2024-05-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
