# Generated by Django 5.0.6 on 2024-05-31 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montos', '0002_cuenta_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='descripcion',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='registrogasto',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registrogasto',
            name='monto',
            field=models.DecimalField(decimal_places=0, max_digits=100),
        ),
        migrations.CreateModel(
            name='RegistroCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('justificacion', models.CharField(max_length=500)),
                ('monto_anterior', models.DecimalField(decimal_places=0, max_digits=100)),
                ('monto_nuevo', models.DecimalField(decimal_places=0, max_digits=100)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montos.cuenta')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montos.registrogasto')),
            ],
        ),
    ]
